apiVersion: v1
kind: Service
metadata:
  name: {{.Values.frontend.applicationName }}
  labels:
    {{- include "foodadvisor-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
  selector:
    {{- include "foodadvisor-chart.selectorLabels" . | nindent 4 }}
